---
# .gitpod.yml

# Define the start script to run Maven
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.fabric8-analytics

# Install necessary tools and dependencies to run
tasks:
  - init: |
      echo "export TERM=xterm" >> $HOME/.bashrc
      echo "export JAVA_TOOL_OPTIONS=" >> $HOME/.bashrc
    command: mvn clean test

jetbrains:
    intellij:
        prebuilds:
            version: stable
